services:
  db:
    image: mysql:8.0.37-debian
    container_name: api-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=api_db
      - MYSQL_ROOT_PASSWORD=apidbpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: apidbpassword
      DB_NAME: api_db
    container_name: api-app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy